version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8

workflows:
  version: 2
  build:
    jobs:
      - heroku/deploy-via-git:
          app-name: practicaldev-circleci
          post-deploy: 
            - run: heroku run rails db:migrate
#       - build:
#           filters:
#             branches:
#               only:
#                 - master

jobs:
  build:    
    environment:
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
      CC_TEST_REPORTER_ID: 42e199897d06699ff0775204bae05b88eb8d3e5ddc28495628aff97b0810f304
      DATABASE_URL: "postgres://postgres@localhost/"
      COVERAGE: true
    docker:
      - image: circleci/ruby:2.6.3-stretch-node-browsers
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache
            - npmcachev2
      - run:
          name: Setup Environment
          command: |
            date --rfc-3339=seconds
            
            # Update bundler
            sudo gem update --system
            gem install bundler
            bundle update --bundler
            
            # Install nvm
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            export NVM_DIR=$HOME/.nvm
            source $NVM_DIR/nvm.sh
            nvm install
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-cache
          paths:
            - vendor/bundle
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache:
          key: npmcachev2
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Tests
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter            
            bundle exec rails db:create
            bundle exec rails webpacker:compile
            bundle exec rails db:schema:load
            ./cc-test-reporter before-build
            bundle exec rspec spec --color --tty
            [ ! -f .approvals ] || bundle exec approvals verify --ask false
            ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json
            yarn test --colors
            ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.lcov.json
            ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
            ./cc-test-reporter upload-coverage
            bundle exec bundle-audit check --update --ignore CVE-2015-9284
            yarn build-storybook
      - heroku/install
      - heroku/deploy-via-git:
          app-name: practicaldev-circleci
          only-branch: master
